[db]
database = "mysql"
url = "root:1234@tcp(localhost:3306)/chatting?multiStatements=true&parseTime=true"

[server]
Port = "1010"
IP = "localhost"

[kafka]
url = "localhost:9292"
clientid = "chat-producer-1"